# Generated by Django 5.0 on 2025-10-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Ano'),
        ),
    ]
